E-COMMERCE/Ecommerce/App_Login/urls.py
from django.urls import path
from App_Login import views

app_name = 'App_Login'

urlpatterns = [

    path('signup/', views.Sign_up, name='signup'),
    path('login/', views.Login_user, name='login'),
    path('logout/', views.Logout_user, name='logout'),
    path('profile/', views.User_profile, name='profile'),


]

E-COMMERCE/Ecommerce/App_Order/urls.py
from django.urls import path
from App_Order import views

app_name = 'App_Order'

urlpatterns = [
    path('add/<pk>/', views.add_to_cart, name="add"),
    path('remove/<pk>/', views.remove_from_cart, name="remove"),
    path('increase/<pk>/', views.increase_cart, name="increase"),
    path('decrease/<pk>/', views.decrease_cart, name="decrease"),
    path('cart/', views.cart_view, name="cart"),

]

E-COMMERCE/Ecommerce/App_Payment/urls.py
from django.urls import path
from App_Payment import views

app_name = 'App_Payment'

urlpatterns = [
    path('checkout/', views.checkout, name="checkout"),
    path('pay/', views.payment, name="payment"),
    path('status/', views.complete, name="complete"),
    path('purchase/<val_id>/<tran_id>/', views.purchase, name='purchase'),
    path('orders/', views.order_view, name="orders"),
]

E-COMMERCE/Ecommerce/App_Shop/urls.py
from django.urls import path
from App_Shop import views

app_name = 'App_Shop'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('product/<pk>/', views.ProductDetails.as_view(), name='product_details'),

]

E-COMMERCE/Ecommerce/Ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

# To show media files()
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Shop.urls')),
    path('account/', include('App_Login.urls')),
    path('shop/', include('App_Order.urls')),
    path('payment/', include('App_Payment.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

E-COMMERCE/Ecommerce/templates/base.html
{% load static %}

<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/main.css' %}">


    <script src="{% static 'fontawesomefree/js/all.min.js' %}"></script>
    <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">


    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

    <title>
        {% block title_block %} E-com | Green {% endblock %}
    </title>
    <style>
        .card {
            height: 350px;
        }

        .card-product:after {
            content: "";
            display: table;
            clear: both;
            visibility: hidden;
        }

        .card-product .price_new,
        .card-product .price {
            margin-right: 5px;
        }

        .card-product .price-old {
            color: #999;
        }

        .card-product .img-wrap {
            border-radius: 3px 3px 0 0;
            overflow: hidden;
            position: relative;
            height: 220px;
            text-align: center;
        }

        .card-product .img-wrap img {
            max-height: 100%;
            max-width: 100%;
            object-fit: cover;
        }

        .card-product .info-wrap {
            overflow: hidden;
            padding: 15px;
            border-top: 1px solid #eee;
        }

        .card-product .action-wrap {
            padding-top: 4px;
            margin-top: 4px;
        }

        .card-product .bottom-wrap {
            padding: 15px;
            border-top: 1px solid #eee;
        }

        .card-product .title {
            margin-top: 0px;
        }
    </style>
</head>

<body>
    {% include 'navbar.html' %}
    <div class="container">
        {% if messages %}
        {% for message in messages %}
        <div {% if message.tags %} class="alert alert-{{message.tags}}{% endif %} alert-dismissible fade show "
            role="alert">

            {{message}}

            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>


        {% endfor %}
        {% endif %}

        {% block body_block %}

        {% endblock %}
    </div>




</body>

</html>

E-COMMERCE/Ecommerce/templates/navbar.html
{% load cart_tag %}


<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'App_Shop:home' %}">Django E-Commerce Project</a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav"
            arial-controls="navbarNav" arial-expanded="false" arial-lable="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a href="{% url 'App_Order:cart' %}" class="nav-link">
                        <i class="fa fa-shopping-cart"></i> Cart
                        <span class="badge badge-light">{{ request.user | cart_total}}</span>
                    </a>

                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false"><i class="fas fa-user-tie"></i>
                        {{request.user.profile.username}}
                    </a>
                    <div class="dropdown-menu" aria-lebelledby="nabbarDropdown">
                        <a class="dropdown-item" href="{% url 'App_Login:profile' %}">Profile</a>
                        <a class="dropdown-item" href="{% url 'App_Payment:orders' %}">Orders</a>
                        <div class="dropdown-diveder"></div>
                        <a class="dropdown-item" href="{% url 'App_Login:logout' %}">Logout</a>
                    </div>
                </li>
                {% else %}
                <li class="nav-item">
                    <a href="{% url 'App_Login:login' %}" class="btn btn-primary">Login</a>
                </li>


                {% endif %}
            </ul>
        </div>
    </div>
</nav>